version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      hexo:
        patterns:
          - hexo*
      dev-tools:
        dependency-type: development
        patterns:
          - '*'
